### ISSUE TITLE
The admin-tools url is not working properly and redirecting in wrong manner to home page

### ISSUE THREAD

**Issue by caaol** [EasyEngine/admin-tools-command#26]
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

ee cli info
+-------------------+-----------------------------------------------------------------------------------+
| OS | Linux 4.11.8-041108-generic #201706290836 SMP Thu Jun 29 12:38:45 UTC 2017 x86_64 |
| Shell | /bin/bash |
| PHP binary | /usr/bin/php7.2 |
| PHP version | 7.2.11-3+ubuntu16.04.1+deb.sury.org+1 |
| php.ini used | /etc/php/7.2/cli/php.ini |
| EE root dir | phar://ee.phar |
| EE vendor dir | phar://ee.phar/vendor |
| EE phar path | /root |
| EE packages dir | |
| EE global config | /opt/easyengine/config/config.yml |
| EE project config | |
| EE version | 4.0.0-rc.1 |
+-------------------+-----------------------------------------------------------------------------------+
wp --allow-root --info
-bash: wp: command not found

 When I visited http://xx.com/ee-admin, I made an authentication, but It still stays on my front page.

**Comment by mrrobot47** [comment]
Closing the issue as this has been fixed througg the following PRs:
https://github.com/EasyEngine/dockerfiles/pull/47
https://github.com/EasyEngine/dockerfiles/pull/52

Try the new stable version. And it will be working.
