### ISSUE TITLE
Admin tools do not work when --public-dir option is specified

### ISSUE THREAD

**Issue by kirtangajjar** [EasyEngine/admin-tools-command#40]
i.e. `ee site create example.com --type=wp --public-dir=current`.

Admin tools do not work as the webroot is at `/opt/easyengine/sites/example.com/current` but the ee-admin directory is created at `/opt/easyengine/sites/example.com/ee-admin`

**Comment by mrrobot47** [comment]
Fixed in https://github.com/EasyEngine/admin-tools-command/pull/41
